### ISSUE TITLE
如何在WebIDE的环境下安排使用WEEX？

### ISSUE THREAD

**Issue by plzj008** [weexteam/article#103]
![image](https://cloud.githubusercontent.com/assets/23072996/19719100/fe5a0448-9b9a-11e6-987b-50283d28ba35.png)

**Comment by plzj008** [comment]
自己顶一个。

**Comment by Jinjiang** [comment]
不管是不是 WebIDE，总之在 bash 下你需要 npm 全局安装 weex-toolkit
p.s. 这里是发表 Weex 相关文章的地方，提问题请到 gitter
谢谢
