### ISSUE TITLE
关于iOS里面<a href="http://www.baidu.com">的拦截

### ISSUE THREAD

**Issue by reeceran** [weexteam/article#106]
你好！
请问iOS里面怎么拦截 a href="http://www.baidu.com"这个标签
我按照android的写法iOS是不可以的
具体注册的module如下：WXEventModule 已经实现了- (void)openURL:(NSString *)url 这个方法，但进不了这个方法里面
[WXSDKEngine registerModule:@"event" withClass:[WXEventModule class]];

**Comment by Jinjiang** [comment]
抱歉这里只适合发表 Weex 的相关文章，技术交流可以来官方 gitter 聊天室 https://gitter.im/weexteam/cn ，新需求或 bug 可以到 Weex 主仓库的 issues https://github.com/alibaba/weex/issues/
感谢理解
