### ISSUE TITLE
iOS关于targetExecuteThread方法的疑惑

### ISSUE THREAD

**Issue by george-luofz** [weexteam/article#107]
在一个download module中，我需要在子线程上做一个download的任务，如果不在targetExecuteThread方法中创建子线程，而是直接在调用方法中创建子线程，下载完毕callback是否能得到执行?
例如：
WX_EXPORT_METHOD(@selector(downloadImgs:sucCallback:failCallback:))
-(void) downloadImgs:(NSDictionary) options sucCallBack:(WXModuleCallback)sucCallback failCallBack:(WXModuleCallback)failCallback{
     ...
     [downloadService downloadImages:imgUrls sucCallBack:^(id result){ // 子线程操作
           ...
          sucCallback(@{@"success":result});// 主线程操作，sucCallback是否能得到执行?
     }failBlock:^(NSError *)error{
          failCallback(@{@"error":error});
     }];
}

**Comment by Jinjiang** [comment]
请不要在这里提问题，使用疑问可以在 gitter，bug 和开放讨论可以在主仓库开 issue
https://github.com/alibaba/weex
谢谢理解
