### ISSUE TITLE
weex iOS集成 pod导入后 编译报错 WXUtility类

### ISSUE THREAD

**Issue by DeveloperQuan** [weexteam/article#110]
extern void WXSwizzleInstanceMethod(_Nonnull Class class, _Nonnull SEL original, _Nonnull SEL replaced);
extern void WXSwizzleInstanceMethodWithBlock(_Nonnull Class class, _Nonnull SEL original, _Nonnull id block, _Nonnull SEL replaced);

这两处地方报错
报错信息:
Declaration of anonymous class must be a definition

**Comment by acton393** [comment]
这个问题，可以提供一下截图， 还有pod 引入的是源码还是framework

这个地方不建议提issue哈， issue 请转义到  [地址](https://github.com/alibaba/weex/issues)
