### ISSUE TITLE
Weex 盲点

### ISSUE THREAD

**Issue by Create-Peace** [weexteam/article#114]
Weex界面的生成码其实就是一段很小的JS，可以像发布网页一样轻松部署在服务端，然后在APP中请求执行,怎么理解？

开发者只需要在自己的APP中嵌入Weex的SDK，就可以通过撰写HTML/CSS/JavaScript来开发Native级别的Weex界面。Weex界面的生成码其实就是一段很小的JS，可以像发布网页一样轻松部署在服务端，然后在APP中请求执行。

这段话是什么意思？weex 开发出来的不是原生应用吗？怎么还是用到服务器端请求啊？

**Comment by demox2026** [comment]
建议楼主细看下工作流

**Comment by Jinjiang** [comment]
请到 Weex 主仓库提问题，这里只是发表文章用的
谢谢配合
