### ISSUE TITLE
使用weex开发出来的app怎样可以通过UiAutomatorviewer抓取元素的resource-id

### ISSUE THREAD

**Issue by evongaf** [weexteam/article#121]
we里定义了id，但是不知道和native 控件属性的影射关系，使用UiAutomatorviewer抓取元素的resource-id为空，请教下如何能够实现增加resource-id

**Comment by Jinjiang** [comment]
请不要在这里提问题…… 这里只用来发表文章的，开 issue 可以到 weex 主仓库，感谢理解
