### ISSUE TITLE
weex 2.x 一直没有官方ui

### ISSUE THREAD

**Issue by SteveCruise** [weexteam/article#156]
1.x的时候，有一些漂亮的.we文件形式的ui，到了2.x，怎么没有对应.vue文件的ui呢，难道让我们自己做么

**Comment by hodgevk** [comment]
有的，在源代码里有

**Comment by SteveCruise** [comment]
在哪在哪？@hodgevk 又找了一遍，并没有

**Comment by hodgevk** [comment]
[地址](https://github.com/apache/incubator-weex/tree/master/examples/vue/include)

**Comment by SteveCruise** [comment]
谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢
