### ISSUE TITLE
安卓下scroller高度设置问题

### ISSUE THREAD

**Issue by fengweiqi** [weexteam/article#169]
有一个这样的需求：
页面上部分是一个scroller，底部固定一个脚部，脚部都有100到200的高度，因此把scroller一部分内容给遮住了，但是又没办法设置scroller高度刚好到脚部顶部，请问有什么办法解决这个问题吗

**Comment by studendzhoujun** [comment]
给scroller里默认最后加上一个cell，这个cell的高和你底部固定的高一样不就ok了
