### ISSUE TITLE
我尝试第一个例子，但是遇到了错误：events.js:160       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by oncealong** [weexteam/article#21]
1 . 运行如下命令，遇到错误： 
E:\workplace\Android\weex>weex tech_list.we
```
info Tue Jun 21 2016 11:48:53 GMT+0800 (中国标准时间)WebSocket  is listening on port 8082
info Tue Jun 21 2016 11:48:53 GMT+0800 (中国标准时间)http  is listening on port 8081
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8082
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

2 . weex版本
E:\workplace\Android\weex>weex --version
```
info 0.1.1
```

3 . tech_list.we的内容：
```
<template>
  <div class="container" >
    <div class="cell">
       <image class="thumb" src="http://t.cn/RGE3AJt"></image>  
       <text class="title">JavaScript</text>
    </div>
  </div>
</template>

<style>
  .cell{margin-top:10 ; margin-left:10 ; flex-direction: row; }
  .thumb {width: 200; height: 200; }
  .title {text-align: center ; flex: 1; color: grey; font-size: 50; }  
</style>
```

**Comment by acton393** [comment]
@oncealong  
```
Error: listen EADDRINUSE 0.0.0.0:8082
    at Object.exports._errnoException (util.js:1007:11)
```

从日志来看，你的是端口`8082`已经被占用

**Comment by oncealong** [comment]
谢谢，已解决。
我根据您的回答使用以下方法解决了。
1 显示占用8082的pid， 在windows下需要增加`-o`选项才会显示pid
`netstat -aon | findstr 8082`
结果：
`TCP    0.0.0.0:8082           0.0.0.0:0              LISTENING       36060`
2 强制关闭。
不知道我的这个具体是哪个程序再用，如果不加`/f`只会发送终止信号，并不会关闭。需要加上`/f`选项来强制关闭。
命令：`taskkill /f -pid 36060`
结果：`成功: 已终止 PID 为 36060 的进程。`
如果不加`/f`，结果如下，但是线程并没有关闭。
`成功: 给进程发送了终止信号，进程的 PID 为 36060。`

**Comment by luics** [comment]
weex issue 还是尽量往 weex 项目提交 https://github.com/alibaba/weex/issues

**Comment by oncealong** [comment]
@luics 
我不是weex项目人员,无法看到这个项目的页面 : )

**Comment by luics** [comment]
@oncealong 据说北京时间 6.30 20:00 [Weex](https://github.com/alibaba/weex/issues) 项目会 public，到时就能看到了 :)

**Comment by duyuan199010** [comment]
C02R48XBFVH5:Weex duyuan797$ weex weex_demo.we 
info Thu Jul 07 2016 10:20:18 GMT+0800 (CST)WebSocket  is listening on port 8082 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8081
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)



请问这个默认端口是在哪里设置的？

**Comment by hjijin** [comment]
@duyuan199010 看看你的nginx配置有没占用了8081 或者8082这些端口吧。

**Comment by jiahut** [comment]
@duyuan199010  sudo weex some.we

**Comment by zhairui** [comment]
查看到了端口，并且Kill掉了，但是端口是node.js占用的，当你再次运行命令是，这些端口又重新被占用，就是重复之前的问题了，这个怎么搞？？？
