### ISSUE TITLE
如何引用另一个weex文件中的内容

### ISSUE THREAD

**Issue by yahooyee** [weexteam/article#41]
引用代码： var test = require('./common.we');           test.methods.test();
common.we中的代码：
<script>
    module.exports = {
        methods:{
            test:function () {
                console.log('test kkkk');
            }
        },
    }
</script>
请问该怎么修改，我用weex  test.we 编译，如何查看我使用的是那个版本的weex-toolkit，本机已安装weex-toolkit@0.3.4

**Comment by terrykingcha** [comment]
很遗憾，require一个`we`文件，是把这个`we`文件作为一个自定义组件引入进来，并可以在主文件中可以使用这个子组件（标签名已这个`we`文件的名字命名），并不能直接访问其中的代码。如果你需要访问一些公共的代码片段，请把他们提取到一个js文件中，并用[commonjs](https://en.wikipedia.org/wiki/CommonJS)模块化方式来导出这些方法，并通过`var test = require('./test.js'); test.method();`使用。

**Comment by lvscar** [comment]
关于Weex 的技术问题请到   https://github.com/alibaba/weex/issues  讨论。   这里仅做文章汇聚用.
