### ISSUE TITLE
几个疑问

### ISSUE THREAD

**Issue by Danielpog** [weexteam/article#49]
1.为什么不遵循w3c标准，生成出来的html结果都是div+span，毫无语义化
2.如何使用字体图标，而不是图片
3.很多css的选择器无法使用，调样式的难度大大提高了
4.用绝对定位或固定定位时，如何让div居中，left，top，bottom，right这些的值用不了百分比

**Comment by luics** [comment]
请提到 https://github.com/alibaba/weex/issues
