### ISSUE TITLE
weex-loader计算容器高度有误

### ISSUE THREAD

**Issue by iceyao** [weexteam/article#60]
同样的内容，通过weex-loader和weex-toolkit编译出来产出的内容容器高度是不一致的，weex-toolkit编译产出高度符合预期，能正常滚动；weex-loader编译产出高度偏差严重，导致内容高度低于外层容器高度而不能滚动。

**Comment by luics** [comment]
请迁移到 https://github.com/weexteam/weex-loader/issues
