### ISSUE TITLE
<wxc-tabbar>组件中的selectedIndex，selectedColor，unselectedColor三个属性无法修改

### ISSUE THREAD

**Issue by wangleigithub** [weexteam/article#61]
weex-components ver.0.2.0版本中，尝试修改selectedIndex，selectedColor，unselectedColor三个属性的值，结果没作用；
尝试的方法：
上级调用者data中设置三个属性，无作用；
在组件style中设置三个值，无作用；
在组件class中设置三个值，无作用；
开发环境：chrome ver.51

**Comment by luics** [comment]
请迁移到 https://github.com/alibaba/weex/issues
