### ISSUE TITLE
wxc-tabbar与image onclick="openurl"有冲突？会导致onclick调用不到？

### ISSUE THREAD

**Issue by Lurkyli** [weexteam/article#69]
我的代码如下：
<template>
    <container>

    <wxc-panel title="width x height" type="primary">
      <wxc-tip type="warning" value="Weex screen width is 750" style="margin-bottom: 20px;"></wxc-tip>
      <wxc-panel title="400 X 400">
        <image class="img" style=" width: 400px; height: 400px;" src="{{img}}" onclick="openurl"></image>
      </wxc-panel>

      <wxc-panel title="200 x 200">
        <image class="img" style=" width: 200px; height: 200px;" src="{{img}}"></image>
      </wxc-panel>
    </wxc-panel>

    <wxc-tabbar tab-items = {{tabItems}}></wxc-tabbar>
    </container>
</template>

<script>
  require('weex-components');
  module.exports = {
    data: {
      dir: 'examples',
      img: '//gw.alicdn.com/tps/i2/TB1DpsmMpXXXXabaXXX20ySQVXX-512-512.png_400x400.jpg',
      tabItems: [
        {
          index: 0,
          title: 'tab1',
          titleColor: '#000000',
          icon: '',
          image: 'http://gtms01.alicdn.com/tps/i1/TB1qw.hMpXXXXagXXXX9t7RGVXX-46-46.png',
          selectedImage: 'http://gtms04.alicdn.com/tps/i4/TB16jjPMpXXXXazXVXX9t7RGVXX-46-46.png',
          src: 'component/tabbar/tabbar-item.js?itemId=tab1',
          visibility: 'visible',
        },
        {
          index: 1,
          title: 'tab2',
          titleColor: '#000000',
          icon: '',
          image: 'http://gtms03.alicdn.com/tps/i3/TB1LEn9MpXXXXaUXpXX9t7RGVXX-46-46.png',
          selectedImage: 'http://gtms02.alicdn.com/tps/i2/TB1qysbMpXXXXcnXXXX9t7RGVXX-46-46.png',
          src: 'component/tabbar/tabbar-item.js?itemId=tab2',
          visibility: 'hidden',
        },
        {
          index: 2,
          title: 'tab3',
          titleColor: '#000000',
          icon: '',
          image: 'http://gtms01.alicdn.com/tps/i1/TB1B0v5MpXXXXcvXpXX9t7RGVXX-46-46.png',
          selectedImage: 'http://gtms04.alicdn.com/tps/i4/TB1NxY5MpXXXXcrXpXX9t7RGVXX-46-46.png',
          src: 'component/tabbar/tabbar-item.js?itemId=tab3',
          visibility: 'hidden',
        }
      ],
    },
    created: function() {
        var bundleUrl = this.$getConfig().bundleUrl;
        console.log('hit', bundleUrl);
        var nativeBase;
        var isAndroidAssets = bundleUrl.indexOf('file://assets/') >= 0;
        var isiOSAssets = bundleUrl.indexOf('file:///') >= 0 && bundleUrl.indexOf('WeexDemo.app') > 0;
        if (isAndroidAssets) {
          nativeBase = 'file://assets/';
        }
        else if (isiOSAssets) {
          // file:///var/mobile/Containers/Bundle/Application/{id}/WeexDemo.app/
          // file:///Users/{user}/Library/Developer/CoreSimulator/Devices/{id}/data/Containers/Bundle/Application/{id}/WeexDemo.app/
          nativeBase = bundleUrl.substring(0, bundleUrl.lastIndexOf('/') + 1);
        }
        else {
          var host = 'localhost:12580';
          var matches = /\/\/([^\/]+?)\//.exec(this.$getConfig().bundleUrl);
          if (matches && matches.length >= 2) {
            host = matches[1];
          }
          nativeBase = 'http://' + host + '/' + this.dir + '/build/';
        }
        var h5Base = './' + this.dir + '/build/';
        // in Native
        var base = nativeBase;
        if (typeof window === 'object') {
          // in Browser or WebView
          base = h5Base;
        }

        for(var i = 0; i < this.tabItems.length; i++) {
            var tabItem = this.tabItems[i];
            tabItem.src = base + tabItem.src;
        }
        // see log in Android Logcat
        //if (this.items.length) console.log('hit', this.items[0].url);
    },
    methods: {
      ready: function (e) {
        var vm = this;
        vm.$on('tabBar.onClick',function(e){
          var detail= e.detail;
          duration = 2;
          this.$call('modal','toast',{
             'message':'tabBar.onClick ' + detail.index,
             'duration':duration});
        });
      },
      openurl:function(e) {
        // TODO
          duration = 2;
          this.$call('modal', 'toast', {
            'message': 'open url',
            'duration': duration
           });
      }
    }
  }
</script>

我的页面功能是：通过tabbar按钮，切换当前页中显示的图片，然后点击页面中的图片进行url跳转。
结果：
我单独写的image操作的页面，openurl的跳转，可以实现。但与wxc-tabbar 集成后，openurl不能跳转了。 有什么要注意的么？

谢谢！

**Comment by Lurkyli** [comment]
src: <string>The custom weex page to display.

我把待切换的页面资源放到src里面后，点击事件正常了。

^_^

**Comment by Jinjiang** [comment]
OK 那这个 issue 我先关掉了，更多使用上的问题将来可以移步我们的中文聊天室 https://gitter.im/weexteam/cn
谢谢
