### ISSUE TITLE
报babel-p lugin-transform-runtime错误

### ISSUE THREAD

**Issue by q624228096** [weexteam/article#90]
ERR! ReferenceError: Unknown plugin "D:\Users\chunhuiwang\AppData\Roaming\n
pm\node_modules\weex-toolkit\node_modules\weex-loader\node_modules\babel-p
lugin-transform-runtime" specified in "base" at 0, attempted to resolve relative
 to "F:\week\week\we"

一直报这个错，不知道什么原因

**Comment by Jinjiang** [comment]
你好，报bug请移步主仓库，使用疑问请移步到weex中文聊天室
谢谢
