### ISSUE TITLE
position:absolute的vDom的100%宽度不生效

### ISSUE THREAD

**Issue by jayli** [weexteam/article#98]
vDom 的 position 样式是 absolute 时，宽度设定100%不生效，比如这段代码，运行后看不到子div有宽度 

```
<div style="width:100%;background-color:red;position:relative;height:400">
    <div style="width:100%;background-color:gray;position:absolute;height:100"></div>
</div>
```

这段代码运行结果：

![](https://gw.alicdn.com/tps/TB1OBboNVXXXXXkXXXXXXXXXXXX-2548-464.png)

在客户端里渲染也是一样的bug

**Comment by Nstd** [comment]
宽度不支持百分比，只支持px，页面默认宽度是750px（会根据屏幕自动缩放），如果想达到100%的效果，就设为750吧
