### ISSUE TITLE
env.deviceWidth 在 iphone5s 里取值不对

### ISSUE THREAD

**Issue by jayli** [weexteam/article#99]
env.deviceWidth 在 iphone里取值不对，这段代码在iphone5s里取出来的是640，应该是750才对，在H5里是对的

```
<template>
    <scroller>
    </scroller>
</template>
<script>
var modal = require('@weex-module/modal');
module.exports = {
    data: {},
    ready: function () {

        this.$getConfig(function (config) {
            var env = config.env;

            // iphone5s里deviceWidth是640，应该是750
            modal.toast({message:env.deviceWidth});
        }.bind(this));
    }
};
</script>
```

**Comment by cxfeng1-zz** [comment]
@jayli  [文档](http://alibaba.github.io/weex/doc/references/api.html#getconfig)里写的是以像素为单位的真实宽度， 在iPhone5s下也就是640。 通过真实的宽高可以做一些脱离750适配的设计， 同时也能计算出750适配后的屏幕高度。

另外H5这边 @Hanks10100  后面也会改成真实的宽高(viewport)，也就是在iPhone5s下是640。

**Comment by Jinjiang** [comment]
这里先关掉了，后续 issue 和讨论在主仓库吧
谢谢
